#!/usr/bin/env python2.7

''' Primary function for mpathic.ools. Currently supports: 

simulate_library
simulate_sublib
simulate_sort
simulate_selection
simulate_mpra
'''

from __future__ import division
import numpy as np
import scipy as sp
import argparse
import sys
import csv

# mpathic only works at the commandline
assert __name__ == '__main__'

# Create argparse parser. 
parser = argparse.ArgumentParser()

# All functions can specify and output file. Default is stdout.
parser.add_argument('-o','--out',default=False,help='Output location/type, by default it writes to standard output, if a file name is supplied it will write to a text file')

# Add various subcommands individually viva subparsers
subparsers = parser.add_subparsers()

import os
print(os.getcwd())

sys.path.append('../')

import src.sortseq_for_doc as sortseq_for_doc

print('made it past first import')

import src.run_tests as run_tests
run_tests.add_subparser(subparsers)


import src.draw as draw
draw.add_subparser(subparsers)

print('made it past third import')

import src.evaluate_model as evaluate_model
evaluate_model.add_subparser(subparsers)

print('made it past 4th import')

import src.preprocess as preprocess
preprocess.add_subparser(subparsers)

print('made it past 5th import')

import src.learn_model as learn_model
learn_model.add_subparser(subparsers)

print('made it past 6th import')

import src.profile_ct as profile_ct
profile_ct.add_subparser(subparsers)

print('made it past 7th import')

import src.profile_mut as profile_mut
profile_mut.add_subparser(subparsers)

print('made it past 8th import')

import src.profile_info as profile_info
profile_info.add_subparser(subparsers)

print('made it past 9th import')

import src.profile_freq as profile_freq
profile_freq.add_subparser(subparsers)

print('made it past 10th import')

import src.predictiveinfo as predictiveinfo
predictiveinfo.add_subparser(subparsers)

print('made it past 11th import')

import src.simulate_library as simulate_library
simulate_library.add_subparser(subparsers)

print('made it past 12th import')

import src.simulate_sort as simulate_sort
simulate_sort.add_subparser(subparsers)

print('made it past 13th import')

import src.simulate_expression as simulate_expression
simulate_expression.add_subparser(subparsers)

print('made it past 14th import')

import src.validate as validate
validate.add_subparser(subparsers)

print('made it past 15th import')

import src.scan_model as scan_model
scan_model.add_subparser(subparsers)

print('made it past 16th import')

# Final incantiation needed for this to work
args = parser.parse_args()
args.func(args=args)









